spring.config.import=optional:file:.env[.properties]

spring.application.name=e-wallet

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

app.initial-admin.enabled=${APP_INITIAL_ADMIN_ENABLED:true}
app.initial-admin.first-name=${APP_INITIAL_ADMIN_FIRST_NAME:System}
app.initial-admin.middle-name=${APP_INITIAL_ADMIN_MIDDLE_NAME:N/A}
app.initial-admin.last-name=${APP_INITIAL_ADMIN_LAST_NAME:Admin}
app.initial-admin.email=${APP_INITIAL_ADMIN_EMAIL}
app.initial-admin.phone=${APP_INITIAL_ADMIN_PHONE}
app.initial-admin.password=${APP_INITIAL_ADMIN_PASSWORD}

otp.length = 6
otp.expiration-minutes = 5
otp.max-attempts = 5

spring.mail.host=${APP_MAIL_HOST}
spring.mail.port=${APP_MAIL_PORT}
spring.mail.username=${APP_MAIL_USER}
spring.mail.password=${APP_MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000
